language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_install:
    - yes | sdkmanager "platforms;android-26"

before_script:


script:
  - ./gradlew lint build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)
