language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26
    - sys-img-x86-google_apis-26
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'