ignore:
  - '**/R.class'
  - '**/*_Impl*'
  - '**/**Module**'
  - '**/DAO**'
  - '**/component**'
  - '**/aplication**'
  - '**/**_Factory**'
  - '**/**Activity**'
  - '**/WalletApplication*'
  - '**/R$*.class'
  - '**/BuildConfig.*'
  - '**/Manifest*.*'
  - '**/*Test*.*'
  - 'android/**/*.*'
  - '**/*_MembersInjector.class'
  - '**/Dagger*Component.class'
  - '**/Dagger*Component$Builder.class'
  - '**/*Module_*Factory.class'